version: '3.10'

services:
  backend:
    build: .
    command: uvicorn mountain_peaks.backend.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app/Mountain-Peaks
    ports:
      - 80:80
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fake_username
      - POSTGRES_PASSWORD=fake_password
      - POSTGRES_DB=mp_db
    expose: 
      - 5432

volumes:
  postgres_data: